name: blaseball-reference

services:
  minio:
    restart: unless-stopped
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    command: server /data
    environment:
      # Credentials for the scripts container was manually set up and is stored
      # as part of the /srv/docker/blaseball-reference/files volume.
      MINIO_API_ROOT_ACCESS: off
    volumes:
      - /srv/docker/blaseball-reference/files:/data
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.middlewares.bbref-files-cors.headers.accessControlAllowMethods: GET
      traefik.http.middlewares.bbref-files-cors.headers.accessControlAllowOriginList: '*'
      traefik.http.routers.bbref-files.entrypoints: https
      traefik.http.routers.bbref-files.middlewares: bbref-files-cors@docker
      traefik.http.routers.bbref-files.rule: Host(`files.blaseball-reference.com`)
    mem_limit: 512m

networks:
  proxy:
    name: proxy
    external: true
