name: json2csv

services:
  app:
    restart: unless-stopped
    image: ghcr.io/society-for-internet-blaseball-research/json2csv
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.json2csv.entrypoints: https
      traefik.http.routers.json2csv.rule: Host(`csv.sibr.dev`)
      traefik.http.services.json2csv.loadbalancer.server.port: 3000
    mem_limit: 512m

networks:
  proxy:
    external: true
    name: proxy
