name: compendium

services:
  app:
    restart: unless-stopped
    image: ghcr.io/yellowstonemagicstats/shinyapp
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.compendium.entrypoints: https
      traefik.http.routers.compendium.rule: Host(`compendium.sibr.dev`)
      traefik.http.services.compendium.loadbalancer.server.port: 3838
    mem_limit: 512m

networks:
  proxy:
    external: true
    name: proxy
