services:
  traefik:
    image: traefik:v3.1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /srv/docker/management/traefik_conf:/etc/traefik:ro
      - /srv/docker/management/traefik_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.sibr-03-hetzner.sibr.dev`)
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.tls.certresolver: prod

networks:
  proxy:
    name: proxy
