name: management

services:
  traefik:
    restart: unless-stopped
    image: traefik:3.1.1
    command:
      - --accessLog.filePath=/data/access.log
      - --accessLog.format=json
      - --api.dashboard=true
      - --certificatesResolvers.acme-dns.acme.dnsChallenge=true
      - --certificatesResolvers.acme-dns.acme.dnsChallenge.disablePropagationCheck=true
      - --certificatesResolvers.acme-dns.acme.dnsChallenge.provider=httpreq
      - --certificatesResolvers.acme-dns.acme.email=certs@sibr.dev
      - --certificatesResolvers.acme-dns.acme.storage=/data/acme-dns.json
      - --entryPoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.middlewares=compression@docker,globalHeaders@docker
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certResolver=acme-dns
      - --entrypoints.https.http.tls.domains[0].main=*.sibr.dev
      - --entrypoints.https.http.tls.domains[0].sans=sibr.dev
      - --entrypoints.https.http.tls.domains[1].main=*.sibr-03-hetzner.sibr.dev
      - --log.level=INFO
      - --metrics.prometheus.manualRouting=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
    environment:
      HTTPREQ_ENDPOINT: http://acme-dns
    networks:
      - acme-dns
      - proxy
    labels:
      traefik.enable: true
      traefik.http.middlewares.compression.compress: true
      traefik.http.middlewares.compression.compress.excludedContentTypes: text/event-stream
      traefik.http.middlewares.globalHeaders.headers.customResponseHeaders.Permissions-Policy: interest-cohort=()
      traefik.http.routers.traefik-metrics.rule: Host(`traefik.sibr-03-hetzner.sibr.dev`) && Path(`/metrics`)
      traefik.http.routers.traefik-metrics.service: prometheus@internal
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/docker/management/traefik_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - acme-dns
    mem_limit: 256m

  acme-dns:
    restart: unless-stopped
    image: ghcr.io/iliana/lego-httpreq-server
    command: [/lego-httpreq-server, --http-addr, "[::]:80"]
    networks:
      - acme-dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      com.centurylinklabs.watchtower.enable: true
    mem_limit: 16m

  watchtower:
    restart: unless-stopped
    image: ghcr.io/containrrr/watchtower:1.7.1
    command: --interval 120 --label-enable --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 32m

  whoami:
    restart: unless-stopped
    image: ghcr.io/traefik/whoami
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.sibr-03-hetzner.sibr.dev`)
    mem_limit: 16m

networks:
  acme-dns: {}
  proxy:
    name: proxy
