name: staticwww

services:
  nginx:
    restart: unless-stopped
    image: nginx:1.26.2
    volumes:
      - /srv/docker/staticwww:/etc/nginx:ro
      - /srv/www:/srv/www:ro
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.staticwww.entrypoints: https
      traefik.http.routers.staticwww.rule: >
        Host(`blog.sibr.dev`) ||
        Host(`bricks.sibr.dev`) ||
        Host(`discord.sibr.dev`) ||
        Host(`etr.sibr.dev`) ||
        Host(`faculty.sibr.dev`) ||
        Host(`files.blaseball-reference.com`) ||
        Host(`files.sibr.dev`) ||
        Host(`hloroscopes.sibr.dev`) ||
        Host(`jq.sibr.dev`) ||
        Host(`levels.sibr.dev`) ||
        Host(`oracle.sibr.dev`) ||
        Host(`research.blaseball-reference.com`) ||
        Host(`research.sibr.dev`) ||
        Host(`sclorigami.sibr.dev`) ||
        Host(`simsim.sibr.dev`) ||
        Host(`snacks.sibr.dev`) ||
        Host(`stacks.sibr.dev`) ||
        Host(`stadium-viewer.sibr.dev`) ||
        Host(`surveys.sibr.dev`)
    mem_limit: 512m

networks:
  proxy:
    external: true
    name: proxy
